# Generated by Django 3.1.12 on 2026-04-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20260402_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvibe',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('both', 'Both')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
