from django.urls import path

from .views import (
    AcceptFriendRequestView,
    CancelFriendRequestView,
    ChangePasswordView,
    ConversationView,
    DeleteMessageView,
    CommentPostView,
    CreateVibeView,
    DeletePostView,
    DeleteVibeView,
    FeedVibesView,
    FriendsListView,
    InboxView,
    LikePostView,
    LoginView,
    MyVibesView,
    NotificationsView,
    PendingRequestsView,
    PostDetailView,
    PostListCreateView,
    RegisterView,
    RejectFriendRequestView,
    ReactToMessageView,
    ReactToVibeView,
    SearchUsersView,
    SendFriendRequestView,
    UnreadCountView,
    UnfriendView,
    UserProfileByIdView,
    ViewVibeView,
    profile_update_view,
    UserProfileView,
)

urlpatterns = [
    path('auth/register/', RegisterView.as_view()),
    path('auth/login/', LoginView.as_view()),
    path('posts/', PostListCreateView.as_view()),
    path('posts/<int:pk>/', PostDetailView.as_view()),
    path('posts/<int:pk>/like/', LikePostView.as_view()),
    path('posts/<int:pk>/comment/', CommentPostView.as_view()),
    path('posts/<int:pk>/delete/', DeletePostView.as_view()),
    path('profile/', UserProfileView.as_view()),
    path('profile/update/', profile_update_view),
    path('profile/change-password/', ChangePasswordView.as_view()),
    path('profile/<int:user_id>/', UserProfileByIdView.as_view()),
    path('users/search/', SearchUsersView.as_view()),
    path('users/<int:user_id>/friend-request/', SendFriendRequestView.as_view()),
    path('users/<int:user_id>/unfriend/', UnfriendView.as_view()),
    path('users/<int:user_id>/cancel-request/', CancelFriendRequestView.as_view()),
    path('friend-requests/', PendingRequestsView.as_view()),
    path('friend-requests/<int:request_id>/accept/', AcceptFriendRequestView.as_view()),
    path('friend-requests/<int:request_id>/reject/', RejectFriendRequestView.as_view()),
    path('friends/', FriendsListView.as_view()),
    path('chat/<int:user_id>/', ConversationView.as_view()),
    path('messages/<int:message_id>/react/', ReactToMessageView.as_view()),
    path('messages/<int:message_id>/delete/', DeleteMessageView.as_view()),
    path('chat/inbox/', InboxView.as_view()),
    path('notifications/', NotificationsView.as_view()),
    path('notifications/unread/', UnreadCountView.as_view()),
    path('vibes/', CreateVibeView.as_view()),
    path('vibes/feed/', FeedVibesView.as_view()),
    path('vibes/mine/', MyVibesView.as_view()),
    path('vibes/<int:vibe_id>/view/', ViewVibeView.as_view()),
    path('vibes/<int:vibe_id>/react/', ReactToVibeView.as_view()),
    path('vibes/<int:vibe_id>/delete/', DeleteVibeView.as_view()),
]
